Social_Media_v3/Models/User_v3.cs
using System.ComponentModel.DataAnnotations;

namespace Social_Media_v3.Models
{
    public class User_v3
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(18, ErrorMessage = "Name length can't be more than 18.")]
        [Display(Name = "User name")]
        public string UserName { get; set; }
        
        [Required]
        public string Password { get; set; }

        public string? Bio { get; set; }

        public string? From { get; set; }
       // public string? To { get; set; }

        public string? MessageTitle { get; set; }
        public string? MessageText { get; set; }

    }
}

Social_Media_v3/Controllers/User_v3Controller.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Social_Media_v3.Data;
using Social_Media_v3.Models;

namespace Social_Media_v3.Controllers
{
    public class User_v3Controller : Controller
    {
        private readonly SocialMediaDbContext _context;

        public User_v3Controller(SocialMediaDbContext context)
        {
            _context = context;
        }
        
        public  IActionResult AllChats()
        {
            var user = _context.Users;

            return View(user);
        }

        public IActionResult CreateMessage(int? id)
        {
            TempData["id"] = id;

            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
       public IActionResult CreateMessage(User_v3 objectUser, string from, string messageText, object? id) // To
       {
            id = TempData["id"];


            var user = _context.Users.FirstOrDefault(x => x.UserName == from);

            if (user == null)
            {
                ModelState.AddModelError("From", "You cannot send a message to non-existent user!");
            }
            else if (user.UserName == from)
            {
                ModelState.AddModelError("MessageText", "You cannot send a message to yourself!");
            }

            StringBuilder sbText = new StringBuilder();
            StringBuilder sbFrom = new StringBuilder();

            if (user.MessageText != null)
            {
                sbText.Append(user.MessageText + " \n" + messageText);

            }
            else
            {
                sbText.Append(messageText);
            }

            foreach (var userFind in _context.Users)
            {
                if (userFind.Id == (int)id)
                {
                    if (user.From != null)
                    {
                        sbFrom.Append(user.UserName + ", \n" + userFind.UserName);
                        user.From = sbFrom.ToString();
                        _context.SaveChangesAsync();

                    }
                    else
                    {
                        user.From = userFind.UserName;
                        _context.SaveChangesAsync();
                    }
                }
            }

            user.MessageText = sbText.ToString();
            _context.SaveChangesAsync();

           return RedirectToAction("AllChats");
       }



        //GET 
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(User_v3 objectUser, string userName, string password)
        {

            foreach (var item in _context.Users)
            {
                if (item.Password == password && item.UserName == userName)
                {
                    TempData["id"] = item.Id;
                    return RedirectToAction("Login2");
                }
            }

            ModelState.AddModelError("UserName", "Not a full name or non-existent user.");
            ModelState.AddModelError("password", "incorrect password.");

            return View();
        }

        public IActionResult Login2(User_v3 objectUser, string userName, string password)
        {
            object id = TempData["id"];

            if (id != null)
            {
                ViewData["id"] = id;
            }

            IEnumerable<User_v3> objectsUserList = _context.Users;
            objectsUserList = objectsUserList.Where(x => x.Id == (int)id);
            return View("ProfileIndex", objectsUserList);
        }

        public IActionResult ProfileIndex(object? id)
        {
            id = TempData["id"];

            IEnumerable<User_v3> objectsUserList = _context.Users;
            objectsUserList = objectsUserList.Where(x => x.Id == (int)id);

            return View(objectsUserList);
        }


        // GET: User_v3
        public async Task<IActionResult> Index()
        {
              return _context.Users != null ? 
                          View(await _context.Users.ToListAsync()) :
                          Problem("Entity set 'SocialMediaDbContext.Users'  is null.");
        }

        // GET: User_v3/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user_v3 = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user_v3 == null)
            {
                return NotFound();
            }

            return View(user_v3);
        }

        // GET: User_v3/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: User_v3/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,Password,Bio,MessageTitle,MessageText")] User_v3 user_v3)
        {
            foreach (var item in _context.Users)
            {
                if (item.UserName == user_v3.UserName && user_v3.Password == item.Password)
                {
                    ModelState.AddModelError("UserName", "Already exists.");
                }
                else if (user_v3.Password == item.Password)
                {
                    ModelState.AddModelError("Password", "Already exists.");
                }
                else if (user_v3.UserName == item.UserName)
                {
                    ModelState.AddModelError("UserName", "Already exists.");
                }

            }


            if (ModelState.IsValid)
            {
                _context.Add(user_v3);
                await _context.SaveChangesAsync();
                TempData["id"] = user_v3.Id;

                return RedirectToAction("ProfileIndex");
            }
            return View(user_v3);
        }

        // GET: User_v3/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }


            var user_v3 = await _context.Users.FindAsync(id);
            if (user_v3 == null)
            {
                return NotFound();
            }

            return View(user_v3);
        }

        // POST: User_v3/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Password,Bio,MessageTitle,MessageText")] User_v3 user_v3)
        {
            if (id != user_v3.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user_v3);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!User_v3Exists(user_v3.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                TempData["id"] = id;

                return RedirectToAction("ProfileIndex");
            }

            TempData["id"] = id;
            return RedirectToAction("ProfileIndex");
        }

        // GET: User_v3/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user_v3 = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user_v3 == null)
            {
                return NotFound();
            }

            return View(user_v3);
        }

        // POST: User_v3/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'SocialMediaDbContext.Users'  is null.");
            }
            var user_v3 = await _context.Users.FindAsync(id);
            if (user_v3 != null)
            {
                _context.Users.Remove(user_v3);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool User_v3Exists(int id)
        {
          return (_context.Users?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Social_Media_v3/Views/User_v3/AllChats.cshtml
@model IEnumerable<User_v3>

@{
    ViewData["Title"] = "Index";
}

<h1>Users communication</h1>


<table class="table table-bordered table-striped" style="width: 100%">
        <thead>
            <tr>
                <th>User name</th>
                <th>Message from</th>
                <th>Message text</th>
            </tr>
            <div class="row pt-4">
                <div class="col-6">
                    <h2 class="text-primary">Users list</h2>
                </div>
                <div class="col-6 text-end">
                </div>
            </div>
        </thead>
        <tbody>
        @foreach(var obj in Model)
        {
            @if (@obj.MessageText != null)
            {
            <tr>
                <td width="25%">@obj.UserName</td>
                <td width="25%">@obj.From</td>
                <td width="50%">@obj.MessageText</td>
            </tr>
            }

        }
        </tbody>
</table>

Social_Media_v3/Views/User_v3/Create.cshtml
@model Social_Media_v3.Models.User_v3

@{
    ViewData["Title"] = "Create";
}

<h1>Create account</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-info">Back to main</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Social_Media_v3/Views/User_v3/CreateMessage.cshtml
@model User_v3

<form method="post" asp-action="CreateMessage">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Send message</h2>
            <hr/>
        </div>

        <div class="mb-3">
            <label asp-for="From">Send message to</label>
            <input type="text" asp-for="From" class="form-control" />
             <span asp-validation-for="From" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="MessageText">Send message</label>
            <input type="text" asp-for="MessageText" class="form-control" />
        </div>
        <div>
            <button type="submit" class="btn btn-primary" style="width:150px">Send message</button>
            <a asp-controller="User_v3" asp-action="ProfileIndex" class="btn btn-secondary" style="width:150px">Back to account</a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Social_Media_v3/Views/User_v3/Delete.cshtml
@model Social_Media_v3.Models.User_v3

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User_v3</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MessageTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MessageTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MessageText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MessageText)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-info" /> |
        <a asp-controller="Home" a asp-action="Index" class="btn btn-outline-warning">Back to account/main!</a>
    </form>
</div>

Social_Media_v3/Views/User_v3/Details.cshtml
@model Social_Media_v3.Models.User_v3

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User_v3</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MessageTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MessageTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MessageText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MessageText)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Social_Media_v3/Views/User_v3/Edit.cshtml
@model Social_Media_v3.Models.User_v3

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User_v3</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <form asp-action="Edit">
        <input type="hidden" asp-for="Id" class="btn btn-outline-info">
        <button type="submit" value="Back to account" class="btn btn-outline-info">Back to account</button>
    </form>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Social_Media_v3/Views/User_v3/Index.cshtml
@model IEnumerable<Social_Media_v3.Models.User_v3>

@{
    ViewData["Title"] = "Index";
}

<h1>All accounts</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MessageTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MessageText)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MessageTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MessageText)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Social_Media_v3/Views/User_v3/Login.cshtml
@model User_v3

<form method="post" asp-action="Login">

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Login</h2>
            <hr/>
        </div>

        @*<div asp-validation-summary="All"></div>*@

        <div class="mb-3">
            <label asp-for="UserName"></label>
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
        
        <div class="mb-3">
            <label asp-for="Password"></label>
            <input asp-for="Password" type="password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>

        </div>
            <button type="submit" class="btn btn-outline-success" style="width:150px">Login</button>
            
            <a asp-controller="Home" asp-action="Index" class="btn btn-outline-info" style="width:150px">Back to main</a>
       
        </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Social_Media_v3/Views/User_v3/ProfileIndex.cshtml
@model IEnumerable<User_v3>

@{
    ViewData["Title"] = "Index";
}
    
<h1>Profile</h1>


<table class="table table-bordered table-striped" style="width: 100%">
        <thead>
            <tr>
                <th>User name</th>
                <th>Bio</th>
                <th>Messege from</th>
                <th>Messege text</th>
            </tr>
            <div class="row pt-4">
                <div class="col-6">
                    <h2 class="text-primary">Users list</h2>
                </div>
                <div class="col-6 text-end">

                @foreach(var item in Model)
                {
                    <a asp-controller="User_v3" asp-action="CreateMessage" asp-route-id="@item.Id" class="btn btn-outline-success">Message</a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-info" >Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete account</a>
                }
                </div>
            </div>
        </thead>
        <tbody>
            @foreach(var obj in Model)
            {
                <tr>
                    <td width="30%">@obj.UserName</td>
                    <td width="30%">@obj.Bio</td>

                    @if(obj.MessageText != null){ // MessageTitle
                        <td width="30%">@obj.From</td>
                        <td width="25%">@obj.MessageText</td>

                }
            </tr>
            }
        </tbody>
</table>